index:
    path: /
    controller: App\Controller\DefaultController::index
#getTodo:
#    path: /todo
#    controller: App\Controller\DefaultController::getTodo
getTodoId:
    path: /todo/{id}
    controller: App\Controller\DefaultController::getTodoId
